---
# tasks file for database
#
   - name : Ensure Oracle Linux is up.
     ping:

   - name : Change Hostname
     hostname:
            name: database

   - name : Change /etc/hosts
     template:
             src: hosts_database.j2
             dest: /etc/hosts

   - name: upgrade all packages
     yum:
        name: '*'
        state: latest

   - name : Install Packages
     yum:
        name: "{{packages}}"  

   - name: Disable SE Linux.
     selinux:
        state: disabled    
   
   - name : Disable firewalld
     systemd:
        name: firewalld
        state: stopped        
        enabled: no

   - name: Modify Kernel Parameters
     blockinfile:
        path:  /etc/sysctl.conf
        marker: "## ANSIBLE MANAGED BLOCK ##"
        insertafter: "# For more information, see sysctl.conf(5) and sysctl.d(5)."
        content: |
           fs.file-max = 6815744
           kernel.sem = 250 32000 100 128
           kernel.shmmni = 4096
           kernel.shmall = 1073741824
           kernel.shmmax = 4398046511104
           kernel.panic_on_oops = 1
           net.core.rmem_default = 262144
           net.core.rmem_max = 4194304
           net.core.wmem_default = 262144
           net.core.wmem_max = 1048576
           net.ipv4.conf.all.rp_filter = 2
           net.ipv4.conf.default.rp_filter = 2
           fs.aio-max-nr = 1048576
           net.ipv4.ip_local_port_range = 9000 65500

   - name : Reload SystemD sysctl -p
     command: /sbin/sysctl -p

   - name: Modify Kernel Parameters
     blockinfile:
        path:  /etc/security/limits.conf
        marker: "## ANSIBLE MANAGED BLOCK ##"
        insertafter: "# End of file"
        content: |
                oracle   soft   nofile   1024
                oracle   hard   nofile   65536
                oracle   soft   nproc    2047
                oracle   hard   nproc    16384
                oracle   soft   stack    10240
                oracle   hard   stack    32768
 
   - name: Edit /etc/pam.d/login file
     blockinfile:
        path:  /etc/pam.d/login
        marker: "## ANSIBLE MANAGED BLOCK ##"
        insertafter: "#-session   optional     pam_ck_connector.so"
        content: |
                session required pam_limits.so     
    
   - name : Reload SystemD sysctl -p
     command: /sbin/sysctl -p
   
   - name : Create groups
     command: groupadd oinstall

   - name : Create groups
     command: groupadd dba

   - name : Create groups
     command: groupadd oper
 
   - name : Add Groups
     group:
         name: oinstall
         gid: 54321  

     group:
         name: dba
         gid: 54322

     group:
        name: oper
        gid: 54323

   - name: Add the user Oracle,Dba,Oper
     user:
         name: oracle
         uid: 54321
         groups: oinstall,dba,oper
         state: present

   - name: Create Directory
     file:
         path: /u01/app/instaladores
         state: directory
         owner: oracle
         group: oinstall
         mode: 0775
         recurse: yes 
   - name: copying database installers
     copy:
        src: linuxamd64_12102_database_1of2.zip
        dest: /u01/app/instaladores
        owner: oracle
        group: oinstall
        mode: 0777 
        
   - name: copying database installers
     copy:
        src: linuxamd64_12102_database_2of2.zip
        dest: /u01/app/instaladores
        owner: oracle
        group: oinstall
        mode: 0777 

   - name: Unarchive a file that is already on the remote machine
     unarchive:
        src: /u01/app/instaladores/linuxamd64_12102_database_1of2.zip
        dest: /u01/app/instaladores
        remote_src: yes
        
   - name: Unarchive a file that is already on the remote machine 2
     unarchive:
        src: /u01/app/instaladores/linuxamd64_12102_database_2of2.zip
        dest: /u01/app/instaladores
        remote_src: yes
        
   - name: Copying Bash Profile
     copy:
        src: .bash_profile
        dest: /home/oracle/
        owner: oracle
        group: oinstall
        mode: 0777     
   - name: copying database installers1
     copy:
        src: db.rsp
        dest: /home/oracle
        owner: oracle
        group: oinstall
        mode: 0777

   - name: copying database installers4
     copy:
        src: cfgrsp.properties
        dest: /home/oracle/cfgrsp.properties
        owner: oracle
        group: oinstall
        mode: 0777             
